FROM golang

ARG T_CONSUMER_KEY
ARG T_CONSUMER_SECRET
ARG T_ACCESS_TOKEN
ARG T_ACCESS_SECRET
ARG GCLOUD_PROJECT
ARG APP_QUERY

ENV T_CONSUMER_KEY=${T_CONSUMER_KEY}
ENV T_CONSUMER_SECRET=${T_CONSUMER_SECRET}
ENV T_ACCESS_TOKEN=${T_ACCESS_TOKEN}
ENV T_ACCESS_SECRET=${T_ACCESS_SECRET}
ENV GCLOUD_PROJECT=${GCLOUD_PROJECT}
ENV APP_QUERY=${APP_QUERY}
ENV GOOGLE_APPLICATION_CREDENTIALS="./service-account-key.json"

COPY ./ /go/src/github.com/mchmarny/tfeel
WORKDIR /go/src/github.com/mchmarny/tfeel

RUN go get ./
RUN go build

CMD ./tfeel --query="${APP_QUERY}"
